name: CI/CD Pipeline

on:
  # Manual trigger
  workflow_dispatch:

  # Trigger on push to develop branch
  push:
    branches:
      - develop
      - develop-10xdevs
      - PS-16-configure-github-action

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

#      - name: Lint code
#        run: npm run lint
#
#      - name: Run unit and integration tests
#        run: npm run test

      - name: Create .env.test file for E2E tests
        env:
          TEST_SUPABASE_URL: ${{ secrets.TEST_SUPABASE_URL }}
          TEST_SUPABASE_ANON_KEY: ${{ secrets.TEST_SUPABASE_ANON_KEY }}
          E2E_USERNAME_ID: ${{ secrets.E2E_USERNAME_ID }}
          E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
          E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
          TEST_USER_EMPTY_FAVS_EMAIL: ${{ secrets.TEST_USER_EMPTY_FAVS_EMAIL }}
          TEST_USER_EMPTY_FAVS_PASSWORD: ${{ secrets.TEST_USER_EMPTY_FAVS_PASSWORD }}
        run: |
          cat > .env.test << EOF
          # Playwright Configuration
          PLAYWRIGHT_BASE_URL=http://localhost:3000

          # Supabase Configuration
          SUPABASE_URL=${TEST_SUPABASE_URL}
          SUPABASE_PUBLIC_KEY=${TEST_SUPABASE_ANON_KEY}
          SUPABASE_ANON_KEY=${TEST_SUPABASE_ANON_KEY}
          PUBLIC_SUPABASE_URL=${TEST_SUPABASE_URL}
          PUBLIC_SUPABASE_ANON_KEY=${TEST_SUPABASE_ANON_KEY}

          # Test Users Configuration
          E2E_USERNAME_ID=${E2E_USERNAME_ID}
          E2E_USERNAME=${E2E_USERNAME}
          E2E_PASSWORD=${E2E_PASSWORD}
          TEST_USER_EMAIL=${TEST_USER_EMAIL}
          TEST_USER_PASSWORD=${TEST_USER_PASSWORD}
          TEST_USER_EMPTY_FAVS_EMAIL=${TEST_USER_EMPTY_FAVS_EMAIL}
          TEST_USER_EMPTY_FAVS_PASSWORD=${TEST_USER_EMPTY_FAVS_PASSWORD}

          # Environment
          NODE_ENV=test
          EOF

          echo "=========================================="
          echo "✓ Created .env.test file"
          echo "File size: $(wc -c < .env.test) bytes"
          echo "Line count: $(wc -l < .env.test) lines"
          echo "=========================================="
          echo "Variables defined (keys only):"
          grep "^[A-Z]" .env.test | cut -d= -f1
          echo "=========================================="
          echo "Checking for empty values:"
          if grep -E "^[A-Z_]+=\s*$" .env.test; then
            echo "⚠️ WARNING: Found empty values above!"
            exit 1
          else
            echo "✓ All variables have values"
          fi
          echo "=========================================="

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Start dev server for E2E tests
        run: |
          npm run dev:e2e > server.log 2>&1 &
          echo $! > server.pid
          echo "Server started with PID $(cat server.pid)"

      - name: Wait for server to be ready
        run: |
          echo "Waiting for server to start on port 3000..."
          for i in {1..30}; do
            if curl -f http://localhost:3000 > /dev/null 2>&1; then
              echo "Server is ready!"
              exit 0
            fi
            echo "Attempt $i/30: Server not ready yet, waiting..."
            sleep 2
          done
          echo "Server failed to start within 60 seconds. Showing server logs:"
          cat server.log
          exit 1

      - name: Run E2E tests
        run: npm run test:e2e

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload Playwright traces
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-traces
          path: test-results/
          retention-days: 30

      - name: Test summary
        if: always()
        run: |
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Linting completed" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Unit tests completed" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ E2E tests completed" >> $GITHUB_STEP_SUMMARY

  build:
    name: Build Production
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build production version
        run: npm run build
        env:
          # Add production environment variables here if needed
          # PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
          # PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
          NODE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist/
          retention-days: 7

      - name: Build summary
        if: always()
        run: |
          echo "## Build Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Production build completed" >> $GITHUB_STEP_SUMMARY
